### ISSUE TITLE
How is it different from ApprovalTests?

### ISSUE THREAD

**Issue by bzaar** [Ackara/Diffa#1]
Not an issue, just a question. Thanks.

**Comment by Ackara** [comment]
I created it because I got tired of waiting for them to port ApprovalTests to netstandard. I took all of the basic features they had and created my own implementation with netstandard. So with that said, Diffa is like a ApprovalTests-Lite but with different class names. Also most of the advance reporters are not present (such as the pdf, wpf, etc.) but if you are looking to just compare text and simple objects, it gets the job done.

Also the only diff tools supported right now are the Visual Studio, BeyondCompare, notepad++ and the system default text editor. More can be added easily, but its just that those are the ones I personally use.
